apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: csi-snapshot-metadata
  name: csi-snapshot-metadata
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: snapshot-metadata
    port: 6443
    protocol: TCP
    targetPort: 50051
  selector:
    app.kubernetes.io/name: csi-hostpathplugin
  sessionAffinity: None
  type: clusterIP
