apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backup-app-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-snapshot-metadata-client-runner
subjects:
- kind: ServiceAccount
  name: backup-app-service-account
  namespace: backup-app-namespace
